server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always # 强制启用ANSI颜色输出
  application:
    name: ai-demo
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql6.sqlpub.com:3311/career_backend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root_backend
    password: pUEDMcWMtbRcqnuI
  # Redis配置
  data:
    redis:
      host: redis-19435.crce178.ap-east-1-1.ec2.cloud.redislabs.com
      port: 19435
      username: default
      password: Kd5PCe6qUkpzwhGCerZb0KJsW5JMn6ZT
      connect-timeout: 2000
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME_QQ}
    password: ${MAIL_PASSWORD_QQ}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            
            enable: false
  # 主应用配置
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.ai: debug
    com.backend.careerplanningbackend.controller.AIController: debug

#阿里云oss配置
aliyun:
  oss:
    endpoint: ${ALY_OSS_ACCESS_KEY_ENDPOINT} # 阿里云OSS的endpoint
    access-key-id: ${ALY_OSS_ACCESS_KEY_ID} # 阿里云OSS的access-key-id
    access-key-secret: ${ALY_OSS_ACCESS_KEY_SECRET} # 阿里云OSS的access-key-secret
    bucket-name: ${ALY_OSS_ACCESS_KEY_BUCKET} # 阿里云OSS的bucket-name

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  type-aliases-package: com.backend.careerplanningbackend.domain.po  # 使用你的实体类包
  configuration:
    map-underscore-to-camel-case: true
#    控制台输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    mapper-locations: classpath:mapper/*.xml

#支付宝沙箱
alipay:
  app-id: 9021000156657096
  # 应用私钥 PKCS#8 PKCS#1 在转化一次
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmLshhw7oj3anIPBtPLWIKulhE3q7i8H4KwGy/1QEECSrwUYjdIpLoay4eXaQsS6Cv7yArDjnuR99AvMLo+veFJHtkxf2TH/5WiGlFYCSEjfjeqsVXLbHnTkjYKQzt+x8faBhFvuoV2VC0xbz+XbcAYDojkJS37r89pity+SwX6b64jBERMAw0w2tiqWuU70cStPU1J16ZzbNV0FRfJ9D0vbVCX7PCzZHdwKv6BmbW9s1zTaXvhFAL+FvSQxbRtBjpXuQe25RQoTtwHhoNTwnG1viYPBVbMeMcPwPkMOaisncRHBATBd8jfIK14oz8JHMktcUc48EwVtNNcqSMwWfBAgMBAAECggEBAI95Em09c0YlyMBkDFvWXa/PZAfJjYnGgbs8mGciOedHFvg2HIh2ogjhCAcVZ3kKridWtxoVBTTQflHA5jIJAovDjHjbauqLk6UXznMj50M942AyZX+3psGBV+ivwEbyKNOPpm0Iv8avQTthAKNHO4iqi2dLGuqVyCwse5SexU+6io773czUWRPQ0Ldhp4ypdki2VruwzpaRnbMwjYgwS0nZeUebry5h4febiqRbartw1Nbt1L/gfT8KGNatmLVq2xU9GopsRXTpqLmMQwJ1HTnMAj88E3xBJaqLtyZAbwLWBrNQiggq76U8X26ymJYGJA2GUBMquvnYab4xaRSTRwECgYEA6afJVIOyrx+YAVEvMi3cIzE52De31JZ2Zsy9T4YR28Q+TRdt8JzSqcmrvTwhLhU9uu3I8zf8h2VkhxHH9EMIxS7ktl0u3rvtl26AYdfpvXgziv7v90ZctRKq9cj01FJfOYwpUQMauF2fNJUtQ4qm96Qi6BNXys+EiY4xt2r22JECgYEAthMrmf78XKJPut/tmCz2Uu4db63rf+9w/zCyQ5hBU8zjPTdnrQhJHYGCOr/ErToKQiuF9RaDCqR41qmH5G1OwiFIJLgAjHBZ+duGRWogxrHour/QFaDNzia++KNJsY5v6Ni2p7HM4iv+4gYc813eYzY3c9c+jo1c/hvGL018tDECgYBeaUanmKNtsZVpCtXIL9GggrZ90F2+T6G9/gKMjH7QzyXhXpM0wxk4M93qE87QYRLVYlltNXUbfHO3RA8IesGjc0RFD7ftlf/1zVegsW6n+VbSVhq+TrcND2L292E+HZ6OkTzsmBWG44V96L0manL242KbZZ12vI0wS715AIaHkQKBgGrLQ7/Ht+39phZOUeX4OWLbF5jxwjgAEZ8cyPKs02R7wK2fWcg8G+aal/AtmwagDHRTYvcmhSYw4k/GkFaDZranHtGqu2ekXqIXCOKeJStmHsOqzjphX1WTlF/yJr9mdG1272vc9feTJqUcQM7eOBqpKk1f6uliMTE6yTvlj0eBAoGAbqS3TDm0PoH9TpyVTi718zow4NC2XTwnglffwmMhtVPsOKSyupfFNvaDq3Ox+XjE/u3NApUD7XmLna/68BoXpW9kBgPI7ynr1hJSRTpUR7/4T/iB2nNtLU9h+krmTjJWV8wZTjgw1GvMGp/DvgOT/yegTczpMFrk8I/QVmGhAEQ=
  # 支付宝公钥
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmme9UKSMq2tyHPKxaXlWWJ6yQmefetBCg2EoL6JX/qw5lzdTLMtpcPZPsgN2+a5LrRnZimE14q0RL2sPGVWKdozffi70K7X5ttZQ8BoiRGSNVKmQLZ1sWxhZoNBWze4kDrcTqKtI02OPwQc+mDhjMQf0w/D5A+0M6jWTwM3KNBlSVABZYE1xmmiEZFiM5nugAwJ2cSyIE/AoIoHYZhkCfXwI9G+by/W2sS2T7RH/tnKHtjtSx+eGeAxFHJyJvznJf34tJRFP9/EgmGLKNnTi1akIG+Wszf3fCox0ZCbkqT0cBd7VOrrmGoChyOtcJqBrbQ76d6JO7lljHl9/4gQWDQIDAQAB
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do # 支付结果异步通知地址
  notify-url: http://pf835785.natappfree.cc/api/alipay/toSuccess # 支付完成后跳转的页面
  return-url: http://localhost:8080/api/alipay/toSuccess  # 支付宝网关，沙箱环境固定为这个