import type { CareerGraphData, CareerGraphMode } from './careerGraph.types'

export const promotionGraphData: CareerGraphData = {
  mode: 'promotion',
  title: '垂直晋升图谱',
  subtitle: '聚焦前端岗位从执行到架构与管理的发展主线',
  currentNodeId: 'senior-frontend',
  nodes: [
    {
      id: 'junior-frontend',
      name: '初级前端工程师',
      level: 'P1',
      type: '执行岗',
      category: 'frontend',
      salaryRange: '8k - 12k',
      experience: '0 - 1 年',
      education: '本科及以上',
      description: '负责基础页面开发、组件复用与日常需求交付，是职业路径的起点阶段。',
      skills: ['HTML/CSS', 'JavaScript', 'Vue 3', 'Git 协作'],
      tags: ['基础开发', '需求实现', '组件维护'],
      recommendedLearning: ['夯实 TypeScript 基础', '完成 2 个业务模块独立交付', '理解前端工程化流程'],
      x: 240,
      y: 60,
      highlightColor: '#60a5fa',
    },
    {
      id: 'mid-frontend',
      name: '中级前端工程师',
      level: 'P2',
      type: '骨干岗',
      category: 'frontend',
      salaryRange: '13k - 20k',
      experience: '1 - 3 年',
      education: '本科及以上',
      description: '能够独立负责中等复杂度业务模块，承担页面性能优化和跨团队协作。',
      skills: ['TypeScript', '状态管理', '接口联调', '性能优化'],
      tags: ['模块负责人', '工程化', '性能优化'],
      recommendedLearning: ['沉淀业务组件库', '建立页面性能分析能力', '提升代码规范与可维护性'],
      x: 240,
      y: 250,
      highlightColor: '#38bdf8',
    },
    {
      id: 'senior-frontend',
      name: '高级前端工程师',
      level: 'P3',
      type: '核心岗',
      category: 'frontend',
      salaryRange: '22k - 35k',
      experience: '3 - 5 年',
      education: '本科及以上',
      description: '主导复杂项目落地，负责架构设计、质量把控和技术方案评审，是当前目标岗位。',
      skills: ['架构设计', '复杂组件封装', '前端监控', '跨端方案'],
      tags: ['当前岗位', '项目主导', '技术方案'],
      recommendedLearning: ['建立前端监控体系', '推动跨端复用能力建设', '加强业务抽象与设计评审'],
      x: 240,
      y: 440,
      isCurrent: true,
      highlightColor: '#6366f1',
    },
    {
      id: 'frontend-architect',
      name: '前端架构师',
      level: 'P4',
      type: '专家岗',
      category: 'architecture',
      salaryRange: '35k - 50k',
      experience: '5 - 8 年',
      education: '本科及以上',
      description: '负责前端架构治理、技术标准建设和复杂系统演进规划，提升团队整体交付效率。',
      skills: ['微前端', '低代码平台', '可观测性', '技术规范治理'],
      tags: ['架构治理', '平台建设', '标准制定'],
      recommendedLearning: ['搭建技术中台思维', '强化复杂系统拆解能力', '沉淀跨团队技术治理方法'],
      x: 240,
      y: 630,
      highlightColor: '#8b5cf6',
    },
    {
      id: 'tech-manager',
      name: '技术经理',
      level: 'M1',
      type: '管理岗',
      category: 'management',
      salaryRange: '45k - 65k',
      experience: '7 年以上',
      education: '本科及以上',
      description: '兼顾技术决策、项目管理与团队培养，推动业务结果与工程效率共同提升。',
      skills: ['团队管理', '项目规划', '资源协调', '人才培养'],
      tags: ['团队管理', '项目推进', '人才培养'],
      recommendedLearning: ['提升跨部门沟通与资源统筹能力', '建立团队成长机制', '结合业务制定技术路线'],
      x: 240,
      y: 820,
      highlightColor: '#14b8a6',
    },
  ],
  edges: [
    {
      id: 'promotion-1',
      source: 'junior-frontend',
      target: 'mid-frontend',
      relationType: 'promotion',
      difficulty: '中',
      requiredSkills: ['TypeScript', '组件抽象', '接口联调', '基础性能优化'],
      duration: '6 - 12 个月',
      description: '从执行需求到独立负责模块，需要形成完整交付意识和稳定的工程实践能力。',
      suggestedLearning: ['完成一个完整业务模块闭环', '参与 Code Review', '建立组件复用意识'],
    },
    {
      id: 'promotion-2',
      source: 'mid-frontend',
      target: 'senior-frontend',
      relationType: 'promotion',
      difficulty: '中高',
      requiredSkills: ['技术方案设计', '复杂状态建模', '性能与稳定性治理', '跨团队协作'],
      duration: '12 - 18 个月',
      description: '从模块负责人进一步成长为项目核心，需要承担复杂项目主导和方案评估职责。',
      suggestedLearning: ['沉淀可复用工程方案', '主导一次复杂需求技术设计', '完善前端监控与异常处理'],
    },
    {
      id: 'promotion-3',
      source: 'senior-frontend',
      target: 'frontend-architect',
      relationType: 'promotion',
      difficulty: '高',
      requiredSkills: ['系统架构设计', '技术治理', '平台化建设', '性能体系化优化'],
      duration: '18 - 24 个月',
      description: '从单项目主导转向架构治理，需要具备跨业务抽象能力和平台化视角。',
      suggestedLearning: ['负责一项平台化建设项目', '制定团队技术规范', '输出可落地架构方案'],
    },
    {
      id: 'promotion-4',
      source: 'frontend-architect',
      target: 'tech-manager',
      relationType: 'promotion',
      difficulty: '高',
      requiredSkills: ['团队管理', '项目组合管理', '资源协调', '目标拆解'],
      duration: '12 - 24 个月',
      description: '从技术专家向管理角色过渡，需要把个人影响力升级为组织影响力。',
      suggestedLearning: ['参与团队招聘与培养', '承担跨团队项目推进', '学习 OKR 与项目节奏管理'],
    },
  ],
}

export const transferGraphData: CareerGraphData = {
  mode: 'transfer',
  title: '横向换岗图谱',
  subtitle: '以当前前端开发岗位为中心，展示可迁移方向与二次延展路径',
  currentNodeId: 'frontend-engineer',
  nodes: [
    {
      id: 'frontend-engineer',
      name: '前端开发工程师',
      level: 'P2 - P3',
      type: '当前岗位',
      category: 'frontend',
      salaryRange: '15k - 28k',
      experience: '2 - 4 年',
      education: '本科及以上',
      description: '具备业务交付、组件开发和工程化能力，是横向拓展的能力中心节点。',
      skills: ['Vue 3', 'TypeScript', '组件化开发', '前端工程化'],
      tags: ['当前岗位', '业务交付', '工程化'],
      recommendedLearning: ['强化接口与数据流建模', '补足服务端思维', '拓展跨端与可视化能力'],
      x: 540,
      y: 360,
      isCurrent: true,
      highlightColor: '#4f46e5',
    },
    {
      id: 'node-backend',
      name: 'Node.js 后端工程师',
      level: 'P3',
      type: '转岗方向',
      category: 'backend',
      salaryRange: '18k - 30k',
      experience: '2 - 4 年',
      education: '本科及以上',
      description: '适合补齐服务端能力，承担 API、鉴权、缓存和服务编排等工作。',
      skills: ['Node.js', 'Express/NestJS', '数据库设计', '鉴权与缓存'],
      tags: ['服务端', 'API 设计', '工程能力'],
      recommendedLearning: ['学习 NestJS 与数据库建模', '熟悉 RESTful / RPC', '掌握日志监控与部署'],
      x: 180,
      y: 150,
      highlightColor: '#0ea5e9',
    },
    {
      id: 'fullstack',
      name: '全栈开发工程师',
      level: 'P3',
      type: '转岗方向',
      category: 'fullstack',
      salaryRange: '20k - 35k',
      experience: '3 - 5 年',
      education: '本科及以上',
      description: '同时具备前后端交付能力，适合承担中小型项目完整闭环开发。',
      skills: ['前后端联调', '服务设计', '部署运维基础', '业务建模'],
      tags: ['全链路', '闭环交付', '业务抽象'],
      recommendedLearning: ['建立后端 CRUD 与鉴权能力', '掌握 Docker 基础', '沉淀完整项目作品'],
      x: 520,
      y: 80,
      highlightColor: '#22c55e',
    },
    {
      id: 'test-dev',
      name: '测试开发工程师',
      level: 'P3',
      type: '转岗方向',
      category: 'qa',
      salaryRange: '18k - 30k',
      experience: '2 - 4 年',
      education: '本科及以上',
      description: '面向质量保障与自动化平台建设，适合对稳定性和流程优化敏感的前端工程师。',
      skills: ['自动化测试', 'CI/CD', '接口测试', '质量平台'],
      tags: ['自动化', '质量保障', '稳定性'],
      recommendedLearning: ['学习 Playwright 与 Jest', '掌握接口测试链路', '建设质量度量看板'],
      x: 870,
      y: 160,
      highlightColor: '#f59e0b',
    },
    {
      id: 'mobile-dev',
      name: '移动端开发工程师',
      level: 'P3',
      type: '转岗方向',
      category: 'mobile',
      salaryRange: '18k - 32k',
      experience: '2 - 4 年',
      education: '本科及以上',
      description: '基于跨端框架或原生能力向移动端演进，适合关注多端体验的前端工程师。',
      skills: ['Flutter/React Native', '移动端适配', '端能力调用', '性能调优'],
      tags: ['跨端', '移动体验', '多端适配'],
      recommendedLearning: ['熟悉跨端框架', '理解移动端生命周期', '学习端侧性能优化'],
      x: 910,
      y: 470,
      highlightColor: '#06b6d4',
    },
    {
      id: 'visual-engineer',
      name: 'WebGL / 可视化工程师',
      level: 'P3 - P4',
      type: '转岗方向',
      category: 'visualization',
      salaryRange: '22k - 38k',
      experience: '3 - 5 年',
      education: '本科及以上',
      description: '聚焦可视化、3D 场景与复杂交互，是比赛展示和大屏业务中的热门方向。',
      skills: ['Canvas/WebGL', 'Three.js', '图形学基础', '数据可视化'],
      tags: ['可视化', '科技感', '复杂交互'],
      recommendedLearning: ['学习 Three.js 与着色器基础', '增强动画编排能力', '积累大屏项目案例'],
      x: 560,
      y: 650,
      highlightColor: '#8b5cf6',
    },
    {
      id: 'lowcode-dev',
      name: '低代码开发工程师',
      level: 'P3',
      type: '转岗方向',
      category: 'lowcode',
      salaryRange: '18k - 32k',
      experience: '2 - 4 年',
      education: '本科及以上',
      description: '负责搭建低代码平台与页面搭建器，强调组件抽象、Schema 设计和可视化编排。',
      skills: ['低代码引擎', 'Schema 设计', '拖拽编排', '组件协议'],
      tags: ['平台化', '配置化', '可视化编排'],
      recommendedLearning: ['研究搭建器设计', '学习 DSL / Schema 模型', '积累平台化思维'],
      x: 210,
      y: 540,
      highlightColor: '#ec4899',
    },
    {
      id: 'backend-architect',
      name: '服务端架构方向',
      level: 'P4',
      type: '延展方向',
      category: 'backend',
      salaryRange: '28k - 45k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '在后端方向继续深入，可以向服务治理和高并发架构演进。',
      skills: ['分布式系统', '缓存与消息队列', '高并发设计', '可观测性'],
      tags: ['高并发', '服务治理', '架构设计'],
      recommendedLearning: ['学习微服务治理', '掌握消息队列与缓存策略', '建立监控告警意识'],
      x: 80,
      y: 40,
      highlightColor: '#0284c7',
    },
    {
      id: 'solution-architect',
      name: '业务解决方案工程师',
      level: 'P4',
      type: '延展方向',
      category: 'fullstack',
      salaryRange: '26k - 42k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '从全栈继续延展，可承担方案设计、交付统筹和复杂业务抽象。',
      skills: ['方案设计', '全链路交付', '需求拆解', '系统集成'],
      tags: ['解决方案', '业务抽象', '交付统筹'],
      recommendedLearning: ['练习业务方案编写', '提升跨角色沟通能力', '熟悉系统集成模式'],
      x: 700,
      y: 20,
      highlightColor: '#16a34a',
    },
    {
      id: 'qa-platform',
      name: '质量平台负责人',
      level: 'P4',
      type: '延展方向',
      category: 'qa',
      salaryRange: '26k - 40k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '在测试开发方向继续成长，可主导测试平台、质量度量与效能体系建设。',
      skills: ['测试平台', '效能度量', '自动化流水线', '稳定性体系'],
      tags: ['质量平台', '效能建设', '体系化'],
      recommendedLearning: ['建立质量指标体系', '打通研发流程数据', '沉淀自动化平台能力'],
      x: 1050,
      y: 90,
      highlightColor: '#d97706',
    },
    {
      id: 'super-app',
      name: '多端应用负责人',
      level: 'P4',
      type: '延展方向',
      category: 'mobile',
      salaryRange: '26k - 42k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '移动端继续深入后，可承担多端架构统一、性能治理和核心体验优化。',
      skills: ['跨端架构', '端侧性能治理', '端能力封装', '应用发布流程'],
      tags: ['多端架构', '性能治理', '应用体验'],
      recommendedLearning: ['理解客户端架构演进', '建立端侧监控体系', '优化启动与渲染性能'],
      x: 1080,
      y: 580,
      highlightColor: '#0891b2',
    },
    {
      id: 'immersive-director',
      name: '沉浸式体验方向',
      level: 'P4',
      type: '延展方向',
      category: 'visualization',
      salaryRange: '28k - 45k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '可视化方向进一步升级后，可承担 3D 交互体验、数字孪生和沉浸式产品方向。',
      skills: ['Three.js', 'Shader', '实时渲染', '体验设计协同'],
      tags: ['数字孪生', '3D 体验', '高表现力'],
      recommendedLearning: ['持续打磨 3D 场景性能', '学习实时渲染流程', '强化设计与技术协同'],
      x: 660,
      y: 790,
      highlightColor: '#7c3aed',
    },
    {
      id: 'studio-platform',
      name: '搭建平台负责人',
      level: 'P4',
      type: '延展方向',
      category: 'lowcode',
      salaryRange: '26k - 40k',
      experience: '4 - 6 年',
      education: '本科及以上',
      description: '低代码方向继续沉淀，可走向企业级搭建平台、设计器与业务中台方向。',
      skills: ['设计器架构', '组件协议', '权限与模板体系', '平台治理'],
      tags: ['搭建平台', '中台', '协议设计'],
      recommendedLearning: ['设计组件协议与模板机制', '梳理平台权限体系', '沉淀配置化渲染能力'],
      x: 40,
      y: 690,
      highlightColor: '#db2777',
    },
  ],
  edges: [
    {
      id: 'transfer-1',
      source: 'frontend-engineer',
      target: 'node-backend',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['Node.js', '数据库基础', '接口设计', '鉴权机制'],
      duration: '4 - 8 个月',
      description: '从前端转向 Node.js 后端，需要补足服务端建模、数据库和服务治理能力。',
      suggestedLearning: ['完成一个包含数据库的后端服务', '学习 NestJS 模块化设计', '掌握 Redis 与日志排查'],
    },
    {
      id: 'transfer-2',
      source: 'frontend-engineer',
      target: 'fullstack',
      relationType: 'transfer',
      difficulty: '中',
      requiredSkills: ['后端 CRUD', '部署基础', '业务建模', '联调能力'],
      duration: '3 - 6 个月',
      description: '全栈方向对前端背景较友好，重点是补齐后端开发和交付闭环能力。',
      suggestedLearning: ['独立完成一个全栈项目', '学习 Docker 基础', '强化接口设计与权限体系'],
    },
    {
      id: 'transfer-3',
      source: 'frontend-engineer',
      target: 'test-dev',
      relationType: 'transfer',
      difficulty: '中',
      requiredSkills: ['自动化测试', '测试框架', 'CI/CD', '质量分析'],
      duration: '3 - 6 个月',
      description: '适合对流程和质量敏感的前端工程师，重点转向测试平台和自动化体系建设。',
      suggestedLearning: ['使用 Playwright 建立 UI 自动化', '熟悉接口测试', '接入持续集成流水线'],
    },
    {
      id: 'transfer-4',
      source: 'frontend-engineer',
      target: 'mobile-dev',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['跨端框架', '移动端调试', '性能优化', '端能力接入'],
      duration: '4 - 7 个月',
      description: '从 Web 向移动端拓展，需要理解端侧生命周期、适配与多端性能特征。',
      suggestedLearning: ['完成一个跨端 Demo', '掌握端侧调试工具', '学习常见移动端性能优化方案'],
    },
    {
      id: 'transfer-5',
      source: 'frontend-engineer',
      target: 'visual-engineer',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['Canvas/WebGL', '图形学基础', '动画编排', 'Three.js'],
      duration: '5 - 9 个月',
      description: '可视化方向强调表现力和复杂交互，适合比赛项目和大屏业务展示。',
      suggestedLearning: ['从 2D 图表过渡到 3D 场景', '学习基础着色器', '积累数据大屏与地图案例'],
    },
    {
      id: 'transfer-6',
      source: 'frontend-engineer',
      target: 'lowcode-dev',
      relationType: 'transfer',
      difficulty: '中',
      requiredSkills: ['组件抽象', 'Schema 设计', '拖拽编排', '平台化思维'],
      duration: '3 - 6 个月',
      description: '低代码方向强调配置化与平台化，适合组件抽象能力强的前端工程师。',
      suggestedLearning: ['设计一个页面搭建器原型', '梳理 Schema 渲染流程', '建立组件协议意识'],
    },
    {
      id: 'transfer-7',
      source: 'node-backend',
      target: 'backend-architect',
      relationType: 'transfer',
      difficulty: '高',
      requiredSkills: ['微服务', '高并发', '缓存与消息队列', '服务治理'],
      duration: '12 - 18 个月',
      description: '在 Node.js 后端方向继续深化，可逐步承担服务治理与架构设计职责。',
      suggestedLearning: ['拆解一个微服务场景', '掌握 MQ 与缓存策略', '完善监控与故障预案'],
    },
    {
      id: 'transfer-8',
      source: 'fullstack',
      target: 'solution-architect',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['方案设计', '系统整合', '业务拆解', '交付统筹'],
      duration: '8 - 12 个月',
      description: '全栈向解决方案方向延展，重点在于更高层级的业务抽象与交付整合能力。',
      suggestedLearning: ['输出业务解决方案文档', '参与需求澄清与方案评审', '强化系统集成能力'],
    },
    {
      id: 'transfer-9',
      source: 'test-dev',
      target: 'qa-platform',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['测试平台建设', '质量指标体系', '研发效能', '数据分析'],
      duration: '8 - 12 个月',
      description: '测试开发进一步成长后，可承担质量平台和效能体系建设工作。',
      suggestedLearning: ['建设质量看板', '沉淀自动化平台能力', '建立缺陷与稳定性指标闭环'],
    },
    {
      id: 'transfer-10',
      source: 'mobile-dev',
      target: 'super-app',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['多端架构', '端侧监控', '应用性能优化', '发布流程治理'],
      duration: '10 - 15 个月',
      description: '移动端方向继续深入后，可承担多端应用架构与核心体验治理。',
      suggestedLearning: ['学习端侧稳定性方案', '建立埋点与监控体系', '优化性能与发布流程'],
    },
    {
      id: 'transfer-11',
      source: 'visual-engineer',
      target: 'immersive-director',
      relationType: 'transfer',
      difficulty: '高',
      requiredSkills: ['Shader 基础', '实时渲染优化', '3D 场景设计', '复杂交互'],
      duration: '10 - 16 个月',
      description: '可视化方向升级后，可迈向沉浸式体验和数字孪生等高表现力场景。',
      suggestedLearning: ['持续打磨 Three.js 场景', '学习图形学核心概念', '增强沉浸式交互设计能力'],
    },
    {
      id: 'transfer-12',
      source: 'lowcode-dev',
      target: 'studio-platform',
      relationType: 'transfer',
      difficulty: '中高',
      requiredSkills: ['设计器架构', '协议设计', '权限体系', '平台治理'],
      duration: '8 - 14 个月',
      description: '低代码方向继续发展后，可成长为企业级搭建平台负责人。',
      suggestedLearning: ['沉淀搭建器核心能力', '完善模板与资产体系', '设计平台治理与权限模型'],
    },
  ],
}

export const careerGraphDataMap: Record<CareerGraphMode, CareerGraphData> = {
  promotion: promotionGraphData,
  transfer: transferGraphData,
}

export const defaultGraphMode: CareerGraphMode = 'promotion'
