#file: noinspection SpellCheckingInspection
debug: true
database:
  host: mysql6.sqlpub.com
  port: 3311
  database: career_backend
  user: <USER>
  password: <PASSWORD>
  pool_size: 10 # 连接池基础大小
  max_overflow: 20 # 连接池最大溢出量
  pool_pre_ping: true # 连接池预检查
  pool_recycle: 3600 # 连接池回收时间，单位秒
communication:
  token:
    secret: <SECRET>
    expire: 1800
vector:
  model_name: text-embedding-v4
  llm_model_name: qwen-max
llm:
  model_name: qwen-max
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  timeout: 120 # 超时时间
  max_retries: 3 # 最大重试次数
  max_concurrent_requests: 3 # 最大并发请求数
  extra: # 额外参数
    temperature: 0.7
pdf:
  model_name: qwen-vl-plus
  extra:
    temperature: 0.1
image:
  model_name: qwen-vl-plus
  suffix: [ "JPG", "JPEG", "PNG", "BMP", "GIF" ]
  max_size: 10 # 最大尺寸 MB
  max_dimension: 4096 # 最大尺寸
  extra:
    temperature: 0.7
test_question:
  model_name: qwen-max
  timeout: 120
  extra:
    temperature: 0.7
growth_plan_agent:
  model_name: glm-5
  extra:
    temperature: 0.3
    recursion_limit: 30 # 最大递归深度
path_config: # 路径配置，需要绝对路径，否则使用默认路径
  temp:
    path: <TEMP_PATH>
    exit_is_clean: true # 程序退出时是否清理临时文件
    run_is_clean: false # 程序运行时是否清理临时文件
    expire: 900 # 临时文件过期时间，单位秒
    cleanup_interval: 60 # 清理间隔时间，单位秒
  log: <LOG_PATH>
  prompt: <PROMPT_PATH>
  data: <DATA_PATH>
milvus:
  local:
    host: 47.110.225.35
    port: 19530
  cloud:
    url: <url>
    password: <token>
chroma_config:
  save_path: <SAVE_PATH>
  model_name: text-embedding-v4
  k: 5
  collection_name:
    default: default_collection
    project_collection: open_source_projects
    intern_collection: internships
    book_collection: books
    video_collection: videos
  extra:
    temperature: 0.7
code_ability:
  model_name: qwen-max
  extra:
    temperature: 0.3
  github_token: <GITHUB_TOKEN>
  gitee_token: <GITEE_TOKEN>
match_analyzer:
  extra:
    temperature: 0.2
redis:
  host: <HOST>
  port: 0
  username: <USERNAME>
  password: <PASSWORD>
  connect_timeout: 2000 # 连接超时时间，单位毫秒
  cache_timeout:
    default: 86400 # 默认缓存超时时间，单位秒
    file_parse: 86400
    code_ability: 7200
    report: 3600
    question: 3600
neo4j:
  url: neo4j+s://3f0cb79d.databases.neo4j.io
  username: 3f0cb79d
  password: <PASSWORD>
other:
  ssl_verify: false
conversation:
  memory:
    save_path: <SAVE_PATH>
    short:
      max_messages: 20 # 最大消息数量
      max_tokens: 10000 # 最大token数量
      compression_trigger_raito: 0.8 # 压缩触发比例
      keep_recent_messages: 8 # 压缩时保留最近的消息数量
      extra:
        temperature: 0.2
    long:
      max_memory_count: 50 # 最多50条记忆
      min_score: 0.6 # 最低记忆分数
      collection_name: user_memories # ChromaDB 集合名称
      extra:
        temperature: 0.2
    extraction:
      extra:
        temperature: 0.2
    compression:
      extra:
        temperature: 0.2
  agent:
    model_name: deepseek-reasoner
    base_url: https://api.deepseek.com
    extra:
      temperature: 0.7