#file: noinspection SpellCheckingInspection
database:
  host: mysql6.sqlpub.com
  port: 3311
  database: career_backend
  user: <USER>
  password: <PASSWORD>
communication:
  token:
    secret: <SECRET>
    expire: 1800
lite_llm:
  model_name: dashscope/qwen-plus
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  timeout: 30 # 超时时间
  max_retries: 3 # 最大重试次数
  extra: # 额外参数
    temperature: 0.7
  qwen:
    model_name: dashscope/qwen3.5-plus
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    timeout: 30
    max_retries: 3
    extra:
      temperature: 0.7
  deepseek:
    model_name: dashscope/deepseek-v3-plus
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    timeout: 30
    max_retries: 3
    extra:
      temperature: 0.7
vector:
  model_name: text-embedding-v4
  llm_model_name: qwen-plus
llm:
  model_name: qwen-plus
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  timeout: 30 # 超时时间
  max_retries: 3 # 最大重试次数
  extra: # 额外参数
    temperature: 0.7
pdf:
  model_name: qwen-vl-plus
  extra:
    temperature: 0.1
image:
  model_name: qwen-vl-plus
  suffix: ["JPG", "JPEG", "PNG", "BMP", "GIF"]
  max_size: 10 # 最大尺寸 MB
  max_dimension: 4096 # 最大尺寸
  extra:
    temperature: 0.7
test_question:
  model_name: qwen-max
  timeout: 60
  extra:
    temperature: 0.7
path_config: # 路径配置，需要绝对路径，否则使用默认路径
  temp: <TEMP_PATH>
  is_clean: true # 程序退出时是否清理临时文件
  log: <LOG_PATH>
  prompt: <PROMPT_PATH>
  data: <DATA_PATH>
milvus:
  local:
    host: 192.168.3.128
    port: 19530
  cloud:
    url: <url>
    token: <token>
